import type { Metadata } from "next";
// Supports weights 100-900
import { NavbarDemo } from "@/components/Navbar";
import "@fontsource-variable/onest";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="light">
      <body
        id="inicio"
        className="bg-charade-50 dark:bg-charade-950 dark:text-charade-50 text-charade-950 transition-all duration-300"
      >
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavbarDemo />
          <div className=" max-w-screen-xl px-5 md:px-14 mx-auto ">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
